name = "file_streams"
version = "0.5.1"
description = "Gleam library that provides access to Erlang file streams."
licences = ["MIT"]
repository = { type = "github", user = "richard-viney", repo = "file_streams" }
links = [
    { title = "Website", href = "https://github.com/richard-viney/file_streams" },
]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
simplifile = "~> 1.4"
